services:
  web:
    build:
      context: .
      target: deps
    image: vagtplan-dev
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
